# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='chat.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
